### ISSUE TITLE
MyMoney investment account design change

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#12]
I wrote a short spec on changes I want to make to investment accounts

[MyMoney investment spec.docx](https://github.com/clovett/MyMoney.Net/files/3272441/MyMoney.investment.spec.docx)

**Comment by clovett** [comment]
Ok, looking at https://www.mint.com/brokerages/ they have these account types I guess:

  *   Credit
  *   Checking
  *   Savings
  *   Brokerage
  *   401k
  *   IRA
  *   Insurance
  *   Loans

And MyMoney has an additional one named “Assets”, and JP added “Rentals” also.

So we could do something similar, renaming “Investment” account to “Brokerage” accounts.  And add a new account type named “IRA” (individual retirement account).  All 401k, IRA, Roth IRA would fit under this category.  So if the pre-tax vs post-tax thing is important I would add that to the account properties, basically the “Roth IRA” would check a box named “Tax free”.  The portfolio reports then can separate tax deferred from tax free accounts so you get a more clear picture of tax implications.  Does this work for you?

Your spec says “Mutual funds and stocks are not tax free, tax exempt, or normally taxes.  It’s the account that defines that behavior.” And I’m not sure I agree with that.  I have a Brokerage account that holds some Municipal Bonds and State Bonds, and these are tax free.   So I’d like to keep the taxable status on individual Securities.

So the only change really would be removing the “Tax deferred” checkbox and replacing it with a “Tax free” checkbox, which you can check on Roth IRA accounts.  I’d rather not hard code “Roth IRA” into the application just in case someone invents a new type of tax free thing in the future.  The assumption would be all other IRA accounts are tax deferred.   Perhaps I could create a brokerage account and hold only tax free municipal bonds in it then I could also mark that account as “tax free”…

Thoughts?

-Chris.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by clovett** [comment]
Oh, and

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by clovett** [comment]
Oh, and I love the idea of better trend analysis reports.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Chris Lovett
Sent: Thursday, June 13, 2019 11:44:42 AM
To: clovett/MyMoney.Net; clovett/MyMoney.Net
Cc: Subscribed
Subject: RE: [clovett/MyMoney.Net] MyMoney investment account design change (#12)

Ok, looking at https://www.mint.com/brokerages/ they have these account types I guess:

  *   Credit
  *   Checking
  *   Savings
  *   Brokerage
  *   401k
  *   IRA
  *   Insurance
  *   Loans

And MyMoney has an additional one named “Assets”, and JP added “Rentals” also.

So we could do something similar, renaming “Investment” account to “Brokerage” accounts.  And add a new account type named “IRA” (individual retirement account).  All 401k, IRA, Roth IRA would fit under this category.  So if the pre-tax vs post-tax thing is important I would add that to the account properties, basically the “Roth IRA” would check a box named “Tax free”.  The portfolio reports then can separate tax deferred from tax free accounts so you get a more clear picture of tax implications.  Does this work for you?

Your spec says “Mutual funds and stocks are not tax free, tax exempt, or normally taxes.  It’s the account that defines that behavior.” And I’m not sure I agree with that.  I have a Brokerage account that holds some Municipal Bonds and State Bonds, and these are tax free.   So I’d like to keep the taxable status on individual Securities.

So the only change really would be removing the “Tax deferred” checkbox and replacing it with a “Tax free” checkbox, which you can check on Roth IRA accounts.  I’d rather not hard code “Roth IRA” into the application just in case someone invents a new type of tax free thing in the future.  The assumption would be all other IRA accounts are tax deferred.   Perhaps I could create a brokerage account and hold only tax free municipal bonds in it then I could also mark that account as “tax free”…

Thoughts?

-Chris.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by andreva7** [comment]
OK.
I would call it “retirement” instead of IRA though.  401K, IRA and DPC can go under that.
I think that’s a good first step.

-Andre

**Comment by clovett** [comment]
Ok, great, is this change something you want to tackle?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by andreva7** [comment]
I have been working on this today.  As I’ve worked through the code, a few naming \ consistency issues have come up.
I am going to write this up later today or tomorrow.

-Andre

**Comment by clovett** [comment]
Ok, sounds good.  JP and I didn’t have good naming conventions, sorry about that.  We should just agree on a coding standard moving forwards, then slowly change the code to that over time, rather than a huge bulk change.  Every time I’ve tried huge bulk changes, invariably some nasty bugs creep in.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by clovett** [comment]
I did some work on this also, and pushed some changes, so please let me know what you think.  Let's iterate on this until you get what you need here.  The change I made adds a "TaxFree" flag to Accounts as you suggested in your spec, which is great for Roth IRA accounts.  The Accounts dialog then shows a TaxStatus ComboBox instead of a check box like this:
 
![image](https://user-images.githubusercontent.com/3336415/154789436-3f0907cc-7a15-437a-9633-ee261cf33fc4.png)

Then I'm deprecating "Retirement" accounts (also as you suggest) you should only need Brokerage accounts, with the specified tax status.  But the system will still work with Retirement accounts if you have them.  But for all intents and purposes they are identical to Brokerage accounts.   Then I modified the Network and Portfolio reports to group things in those buckets "TaxFree", "TaxDeferred" and "Taxable" where "Gains" are only shown if it is not TaxFree so the Portfolio Reports lists:

- Tax Free Invgestments
- Tax Deferred Invgestments
- Taxable Investments

So please take the main branch for a spin and let me know what you think, thanks.

**Comment by clovett** [comment]
Portfolio Report:

![image](https://user-images.githubusercontent.com/3336415/154790172-a72f99e5-92ec-4e88-8f4d-b2399e439d1a.png)

**Comment by jpdup** [comment]
Agree on the incremental improvement for Naming convention.
I have not used the Reports; mainly due to my complex 3 way countries taxing use cases  So both of you have more skin in the game regarding these reports. This year I intent to adopt the report. I'll have a better opinion in a month from now.

**Comment by andreva7** [comment]
I was playing around with it and found an existing bug:
If you have stock accounts with negative cash values - because you borrowed on margin -  the cash amount does not show up (there is a check for cash > 0 in the code), but it does get included in the math, so subtotal and totals end up smaller then the value of the account. It also ends up applying to to taxable value..
As a general rule cash is not taxable (ignoring that cash may have come from a recent stock sale and now you have to pay the actual taxes), so I think cash (both positive and negative) should be taken out from the report, and the math or made it's different section.

**Comment by andreva7** [comment]
And yes, I like the nomenclature.

**Comment by clovett** [comment]
> As a general rule cash is not taxable (ignoring that cash may have come from a recent stock sale and now you have to pay the actual taxes), so I think cash (both positive and negative) should be taken out from the report, and the math or made it's different section.

Good point, I removed cash from the Portfolio report.  Cash balances are covered in the Networth report and so no need to try and repeat that information in the Portfolio report.  I pushed these changes.

**Comment by clovett** [comment]
@andreva7 would you be ok with calling this issue "closed" ?
