### ISSUE TITLE
Fiscal year support

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#21]
I am now the treasurer of the school PTA.
Reports and charts in MyMoney are all based on calendar years, but the school has a fiscal year that starts July 1. Having an option to set a fiscal year start that all the reports (like cash flow) and charts (category \ subcategory spend, per year) is necessary to make all these meaningful.

Thanks.

**Comment by clovett** [comment]
Good idea.

**Comment by andreva7** [comment]
Thanks for the quick turnaround. It’s looking good. The history chart works as expected.

The cash flow report will be very useful as well.

I noticed a problem with history charts – I think unrelated to the above change:
I have a category (A) which has a few sub categories (A:B, A:C, etc) , some of which are expenses and some are income. The school is doing well, so the total income is higher than the total expense 😊
When I look at the history chart for A, it always shows a negative number, whether I set A as income, expense or none.

Thanks,

-Andre

**Comment by clovett** [comment]
yes, that is expected, the current implementation uses a simple heuristic to determine whether to "flip" the chart and make all negatives positive or not, and it is simply based on what is the most common data item in the chart, more negatives = flip the chart.  This heuristic was implemented rather than tying the clip to the "category" because as you already show above, some charts contain a mix of income and expenses.  The "View by payee" is another kind that can have a mix, for example, home depot might have expenses and refunds.  Does this make sense?

**Comment by clovett** [comment]
I just published new version with support for fiscal year in the Cash Flow Report, see updated documentation:
https://github.com/clovett/MyMoney.Net/wiki/Cash-Flow-Report

**Comment by clovett** [comment]
And finally, I added "Fiscal Year Start" to W2 tax report and I added a new "Set Tax Year" feature for transactions, see the bottom of this page: https://github.com/clovett/MyMoney.Net/wiki/W2%20Report

**Comment by andreva7** [comment]
Looks good!

Thanks,

-Andre

**Comment by clovett** [comment]
Cool, if you think "Fiscal Year Start" is done, please go ahead and close the issue, thanks.

**Comment by andreva7** [comment]
Looking good. Thanks.
