### ISSUE TITLE
Wrong coloring on account balance

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#36]
In the accounts window, when you select an account, if the account has a negative balance the red coloring goes away - it shows black.

**Comment by andreva7** [comment]
Dup

**Comment by lovettchris** [comment]
actually this is not a dup, this one is by design.  Since the "Selection" background color uses your Windows Accent Color, I cannot guarantee that the background color doesn't "clash" with red.  For example, my accent color is Teal, and the red is barely readable, so the selected item drops the red coloring.

![image](https://user-images.githubusercontent.com/18707114/156634383-476818de-c638-4bc0-ad1f-f3c177d099dd.png)

**Comment by andreva7** [comment]
OK. Well, keep my "vote" as requesting a design change to always keep it red. You can see if you get more feedback about this.

-Andre

**Comment by lovettchris** [comment]
Sure, on previous products I worked on we also did clever color manipulations in the HSL space to ensure the 2 colors in question had a good 'contrast' separation... which we could do here also... but red on Teal is pretty hard to fix, but it could only in that case switch to black (or white) but if your accent color is something else more muted such that red on that accent has a fine contrast then we keep the red, sort of thing...

**Comment by lovettchris** [comment]
The other fix would be to stop using accent color for our list & grid item selection background color, and use a fixed "themed" color instead such that we can ensure red always looks good on that color...  it would probably be a gray color.

**Comment by andreva7** [comment]
That would work. I don't think using the accent color adds more value that we lose with the red turning to black.

-Andre
