### ISSUE TITLE
Renaming an account breaks the link to existing statements

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#50]
Renaming an account breaks the link to existing statements

**Comment by clovett** [comment]
Fixed in 2.0.0.9, but the fix has some limitations.  Namely, if you rename the account the folder for statements (and attachments) is renamed accordingly -- before you click "Save" (so that attachments and statements continue to work) - but that means if you don't click "Save", the folder is left out of sync so that next time you reload Money it will not find the renamed folders - you will have to manually rename them back to the old account names.

**Comment by andreva7** [comment]
You have to save and restart mymoney for things to work, but that's fine for me.
