### ISSUE TITLE
Fiscal year

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#65]
The Parent teacher association and the school are not always fast on handling checks.
I write a check in June and it gets cashes in September, which is a different fiscal year for when the expense really occured.
Because the bank balances have to work, the date has to be September.

Has there been a though about being able to put a date to enable the expense to show up in the previous (correct) fiscal year?

**Comment by clovett** [comment]
Yes you can right click a transaction and select "Set Tax Year..."

**Comment by andreva7** [comment]
I tried this and it does not appear to work. Given the name, does this only apply to the "Tax" report? I am using the cash flow report to track spending per category across the years.

**Comment by clovett** [comment]
Ah, that is probably it, it only applies to the tax report right now.

**Comment by clovett** [comment]
what month do you want this transaction to show up in ?  Since you can only set a tax year, I'd imagine in this case you want to have it show up in the same "fiscal year" as the September date, suppose that is sept 2021, and if your fiscal year starts on July 2021 then I'd imagine you want the transaction to move from June show up in the 7/1/2021 column of the cash flow report?  If you want it to show up in the September column, then we need more info - we need a new feature, like "check clearance date" or something.  I normally just fudge the dates on my check transactions to the clearance date when the clearance comes in since this is all the bank really cares about.  I can always open the attachment to see a copy of the original check if I need to check what the date was when I wrote the check....  ?

**Comment by andreva7** [comment]
I wrote the check in June 2022 - that's when we expense really happened. I would like the expense to show up in the 2021-2022 fiscal year, that ends July 31st 2022.
The check got cashed in September 2022, so on the bank statement it will show the debit from the account in september2022.

If I change the cashed date to be in June, the fiscal year numbers will work, but the account balance will be confused from June through September.

If the Tax year setting also applied to the fiscal year calculation, that would work for me.

-Andre

**Comment by clovett** [comment]
Yep, I understand.  Anyway, I changed "Set Tax Year" to "Set Tax Date" so you could now set the tax date to June 2022 top match when you wrote the check.  See d3ea577bf63779db30535d448e865eb5aea9284d.

I have not yet updated the cash flow report to use this.

**Comment by clovett** [comment]
Cash Flow report now uses the tax date on a transaction, if one is set.  See 8cde0858ae20b5b395121ab1a1c031ae43de0a9d

**Comment by andreva7** [comment]
Works great! thank you.
